### ISSUE TITLE
Make immstruct instantiable?

### ISSUE THREAD

**Issue by Dashed** [omniscientjs/immstruct#10]
I'm mulling over an idea to make immstruct instantiable. Pretty much in the same manner that `EventEmitter` is instantiable. 

I'm suggesting this so that something like `new immstruct().instances` would be compartmentalized. I have a library that's a work-in-progress that decorates the `immstruct`, and one feature I have is that it creates an associated meta-structure for a given immstruct structure.

**Comment by mikaelbr** [comment]
Fixed in 84a35e1eded0d55bf82ea5841796e424019c5938

**Comment by mikaelbr** [comment]
Usage is

```js
var local = new immstruct.Immstruct();
```

Default usage (without own instance) remains the same as before.

**Comment by Dashed** [comment]
Awesome thanks.
