### ISSUE TITLE
Revise how `self.current` syncs

### ISSUE THREAD

**Issue by dashed** [omniscientjs/immstruct#12]
Following conversation from: https://gitter.im/omniscientjs/omniscient/archives/2014/12/17

~~Following lines seem redundant:
https://github.com/omniscientjs/immstruct/blob/d97662dcbe51df249430eca95eb589367c3bc30b/src/structure.js#L58-L60~~

If `self.current === oldRoot`, you can just do `self.current = newRoot`, otherwise you'll need to splice subtrees to resync.

I'm raising this issue, because on delete event: `return self.current = newRoot;`
https://github.com/omniscientjs/immstruct/blob/d97662dcbe51df249430eca95eb589367c3bc30b/src/structure.js#L55

~~I'm unsure how to replicate out-of-sync Immutable collection.~~
EDIT: see comments below

**Comment by rattrayalex** [comment]
Wow, what a terrific pair of explanations! Open source is amazing. Thanks guys!!
