### ISSUE TITLE
Listen for changes to specific paths

### ISSUE THREAD

**Issue by torgeir** [omniscientjs/immstruct#18]
We can easily add listeners to when specific pieces of data inside a structure changes.

Of course, you can aldready do 

```js
structure.on('change', (path, _, _) => {
  if (path === 'this.path') doThis();
  else if (path == 'something.else') doSomethingElse();
});
```

But something along the lines of this would be nice

```js
structure.on('change', 'this.path', doThis);
structure.on('change', 'something.else', doSomethingElse);
```

**Comment by mikaelbr** [comment]
Reference cursors should cover this part, no? #30

**Comment by Dashed** [comment]
Yep. This should be closed.
