### ISSUE TITLE
Computed values based on sets of cursors

### ISSUE THREAD

**Issue by torgeir** [omniscientjs/immstruct#19]
This is more an idea than a specific feature suggestion.

I often find myself wanting to update pieces of a structure based on when other specific pieces of a structure or other structures change; think knockout computed observables but with cursors.

How about

```js
var m = immstruct({ m: 42 }).cursor('m');

var somewhere = immstruct({ somewhere: { else: { n : 42 } } });
var n = somewhere.cursor(['somewhere', 'else', 'n']);

var result = immstruct({ sum: undefined });
immstruct.listen([m, n], (m, n) => result.set('sum', m.deref() + n.deref());
```

**Comment by mikaelbr** [comment]
You can kind of do the this using #60, no? So this can be closed?
