### ISSUE TITLE
Pass in keyPath for swap and next-animation-frame events

### ISSUE THREAD

**Issue by dashed** [omniscientjs/immstruct#21]
Surprised it doesn't do this.

Pass in `keyPath` for `swap` and`next-animation-frame` events to better match 
`onChange?: (newValue: any, oldValue?: any, keyPath?: Array<any>) => any`
signature for Cursors:
https://github.com/facebook/immutable-js/blob/7cd0bc61b6552e88626587be4ff4adc5a9759c5a/contrib/cursor/index.d.ts#L44-L57

**Comment by singggum3b** [comment]
still missing keypath in 'next-animation-frame' event?
