### ISSUE TITLE
Add user defined changeListeners

### ISSUE THREAD

**Issue by Dashed** [omniscientjs/immstruct#23]
Just throwing ideas around.

We should have a way to add user-land `changeListeners`: https://github.com/omniscientjs/immstruct/blob/3ff9f1291e2755933fe75cc8562bed3cc8ca1e1f/src/structure.js#L72-L75

```js
var Structure = require('immstruct/structure');
var s = new Structure({
  key: 'foo', // default random string
  data: someObject, // default empty object
  withHistory: true, // default `false`
  changeListeners: [ ... ]
});
```

There was a use-case where I wanted to do this, and I wanted to be able to "block" `changeListeners` from propagating.

**Comment by mikaelbr** [comment]
I don't think this is the best approach for us now. I think this may require to much knowledge of the inner workings, and maybe be too dependent on order.
