### ISSUE TITLE
Immstruct -> React -> shouldComponentUpdate Implementation?

### ISSUE THREAD

**Issue by ArnoBuschmann** [omniscientjs/immstruct#28]
Not an issue but a question...

When using Immstruct together with Omniscient, Omniscient provides an "efficient, centrally defined shouldComponentUpdate". 

What if bundling Immstruct together with React? Does it make sense to use the PureRenderMixin to implement schouldComponentUpdate? http://facebook.github.io/react/docs/pure-render-mixin.html

And would there be disadvantages in doing so, compared to the Omniscient solution?

**Comment by Dashed** [comment]
Omniscient's shouldComponentUpdate does **deep equality check**. 

PureRenderMixin does **shallow equality check**, as noted in the warning box: http://facebook.github.io/react/docs/pure-render-mixin.html

You can certainly use PureRenderMixin, but you lose equality checking for complex data structures. 

-----


You can use Omniscient's shouldComponentUpdate directly, and it'll be just the same step as using `PureRenderMixin`:
```js
var mixin = {
  shouldComponentUpdate: require('omniscient/shouldupdate')
};
```

**Comment by ArnoBuschmann** [comment]
Ah, thanks for clarification, Dashed.

**Comment by torgeir** [comment]
The pure render mixin shallow equal-checks both props and state, if either changes a component will rerender. 

Omniscient's primary concern is cursors of immutable data passed as props, and it will do *shallow* reference comparisons of these and decide to rerender or not. 

Additionally, for where cursors are not applicable, it will *deep* equal check properties of props that are not cursors, and a component's state.
