### ISSUE TITLE
Create reference cursor from a cursor.

### ISSUE THREAD

**Issue by Dashed** [omniscientjs/immstruct#33]
This:

```js
let cursor = structure.cursor(keyPath);
let everlasting = structure.reference(cursor);
```

This is needed for this: https://github.com/omniscientjs/immstruct/issues/19

**Comment by mikaelbr** [comment]
This might require us to use internals of Immutable.js.

**Comment by Dashed** [comment]
Yes it depends on internals: https://github.com/facebook/immutable-js/blob/7d69f95c5227c88c6a1be8271abc6686aeda94bf/contrib/cursor/index.js#L44

There's no official exposed API for cursor's keypath.
