### ISSUE TITLE
Working examples for React -> Immutable -> Immstruct?

### ISSUE THREAD

**Issue by ArnoBuschmann** [omniscientjs/immstruct#35]
Hi guys,

I know you are mostly concerned about Omniscient but for people who want to stay with React only, I wonder, if there are nice examples already of stacks using React -> Immutable -> Immstruct?

Basically this question is about experiences, problems that might pop up, advantages/disadvantages compared to other solutions such as Omniscient or Morearty.

**Comment by mikaelbr** [comment]
I use Immstruct with React on a project for a client, and the flow is pretty much just like with Omniscient. Omniscient is more or less just an implementation of `shouldComponentUpdate`. 

On said project I use PureRenderMixin (http://facebook.github.io/react/docs/pure-render-mixin.html) as `shouldComponentUpdate`, only with support for cursors. I think at some point I will remove this pure render mixin and just use Omniscients `shouldComponentUpdate` instead, as that covers more edge cases, is tested, and has better support for complex props and cursors.

**Comment by ArnoBuschmann** [comment]
So to use Omniscients should ComponentUpdate right away one could do
```javascript
var mixin = {
  shouldComponentUpdate: require('omniscient/shouldupdate')
};
```
without having to get the entire Omniscient library bundled but only the needed parts?

**Comment by mikaelbr** [comment]
Correct! Omniscient wouldn't even be in your bundle if you're using browserify/webpack

**Comment by ArnoBuschmann** [comment]
Yes, Webpack. Nice! It is neat actually, that Immstruct is decoupled from Omniscient. Going to try it out now.

**Comment by mikaelbr** [comment]
Thanks. That's one of our key goals, having modularized code, allowing you to choose what you want.

**Comment by torgeir** [comment]
Here's a running example with debugging enabled, so you can see `shouldComponentUpdate` do its work

```js

```

**Comment by ArnoBuschmann** [comment]
Oh nice, yes, helps, thanks @torgeir! Already playing with it right now and
```javascript
shouldUpdate.debug();
```
comes in handy :)

**Comment by ArnoBuschmann** [comment]
@torgeir hm, when I install your github repo I get for
```javascript
var shouldUpdate = require('omniscient/shouldupdate');
error: module cannot get resolved
```
So what I already did before in my own project (same error) was to install the Omniscient npm module and:
```javascript
var shouldUpdate = require('omniscient').shouldComponentUpdate;
shouldUpdate.debug(); // but getting an error here -> has no method debug
```
Do you have a hint for me how I can fix this to get the debugging?

**Comment by torgeir** [comment]
Oh, you're right, this is what you'll be able to do when we bump the omniscient version on npm (its on master now).

I updated the example to be compatible with whats on npm https://github.com/omniscientjs/immstruct-react/blob/master/js/app.js#L4-L6

Alternatively, if you'd like to try the current master you could

```
npm i -S omniscientjs/omniscient
```

**Comment by ArnoBuschmann** [comment]
Great, works! :) The debugging is so useful.

**Comment by ArnoBuschmann** [comment]
@torgeir next question :)

When I want to use reference cursors with React, it seems I need
```javascript
var forceUpdateOn = require('omniscient-mixins/mixins/forceUpdateOn');
```
But after installing the npm package omniscient-mixins it seems forceUpdateOn is not part of it yet, maybe because you just indroduced reference cursors?

**Comment by ArnoBuschmann** [comment]
Next question in conjunction with reference cursors is, how I could properly use the Omniscient forceUpdateOn mixin with React?

I tried:
```javascript
var forceUpdateOn = require('omniscient-mixins/mixins/forceUpdateOn');
var timeReference = data.reference('timer', 'time');
var refreshOnTimeReferenceMixin = forceUpdateOn(timeReference);
```
and
```javascript
var Time = React.createClass({
  mixins: refreshOnTimeReferenceMixin,
  ...
```
But this doesn't lead to any updates. When I set 
```javascript
this.forceUpdate();
```
combined with an interval, the clock works well.

**Comment by torgeir** [comment]
Yes, with react you need an array of mixins, omniscient would handle this for you though
https://github.com/omniscientjs/omniscient/blob/master/component.js#L124-L126

**Comment by mikaelbr** [comment]
> I tried:

> ```js
> var forceUpdateOn = require('omniscient-mixins/mixins/forceUpdateOn');
> var timeReference = data.reference('timer', 'time');
> var refreshOnTimeReferenceMixin = forceUpdateOn(timeReference);
> ```

Also remember, cursor-paths are defined as lists. So it would be `data.reference(['timer', 'time'])`

**Comment by mikaelbr** [comment]
I'm closing this for now. Feel free to re-open or post new issues on further questions or problems.
