### ISSUE TITLE
Serializing and deserializing Immstruct structures (application state).

### ISSUE THREAD

**Issue by ArnoBuschmann** [omniscientjs/immstruct#38]
I just wonder, could we serialize/deserialize Immstruct structures with the same approach Morearty comes up with?

https://github.com/moreartyjs/moreartyjs/wiki/Serializing%20application%20state

**Comment by mikaelbr** [comment]
You can actually use the transit-js helper in the same way (from testing out):

```
> var structure = immstruct({ arr: [1, 2, 3] });
> var serializedState = TransitSvc.toTransit(structure.current);
> serializedState
'{"arr":[1,2,3]}'

> var deserializedState = TransitSvc.fromTransit(serializedState)
> deserializedState
Map { arr: List [ 1, 2, 3 ] }
```

However, there are no existing API for replacing an entire state (with/without) history for immstruct. You can "push" a new state (allowing you to undo from the update), by using update as usual:

```js
// having `deserializedState` and `structure` from above
structure.cursor().update(_ => deserializedState);
```

**Comment by ArnoBuschmann** [comment]
Thanks for your evaluation, @mikaelbr.
