### ISSUE TITLE
Assigning arguments causes build error

### ISSUE THREAD

**Issue by frederickfogerty** [omniscientjs/immstruct#46]
The declaration of `var arguments` causes a build error because it is a strict violation.

https://github.com/omniscientjs/immstruct/blob/master/src/structure.js#L453

`Module build failed: SyntaxError: /Users/frederickf/Programming/react-d3/node_modules/immstruct/src/structure.js: Binding arguments in strict mode (260:6)`

**Comment by Dashed** [comment]
@frederickfogerty Mind sending PR?

**Comment by frederickfogerty** [comment]
Sure, can do.

**Comment by frederickfogerty** [comment]
Done, I'm loving this repo btw! And I somehow made a PR on my own fork as well (－‸ლ)
