### ISSUE TITLE
Some things are covered in the readme, and some are covered in the API reference

### ISSUE THREAD

**Issue by jtremback** [omniscientjs/immstruct#61]
For instance, the API reference does not cover `deref`.
Might be good to combine them in some way, separate their roles entirely, or make one a superset of the other.

**Comment by Dashed** [comment]
Glancing, I can probably tell you that the `README` may not be up to date with master.

You may be better off reading the source to grok it.

**Comment by jtremback** [comment]
Is increasing adoption of this framework currently a priority or is it still in a more experimental development phase?

**Comment by mikaelbr** [comment]
Most of the README should be mostly up to date, with a few exceptions. You can find most information you need on the homepage (http://omniscientjs.github.io).

The documentations doesn't originally cover `deref` as it is not a implementation of neither Omniscient or Immstruct, but it is Immutable.js Cursor lib. I get that this can make it harder to get to initially, but it isn't practical for Immstruct to document Immutable.js as well as Immstruct, if that makes any sense?

**Comment by jtremback** [comment]
Oh I had no idea that deref() was from Immutable.

**Comment by mikaelbr** [comment]
Immstruct can kind of be looked on as a cursor factory/extension. So every time you do `.cursor()` you get a Immutable.js cursor.
