### ISSUE TITLE
Are .on and .observe the same thing?

### ISSUE THREAD

**Issue by jtremback** [omniscientjs/immstruct#62]
Looks like it, from the todoMVC app. Docs make no mention of `.on`.

**Comment by Dashed** [comment]
They're not the same thing.

`.on` is for `Structure` instances which extends an eventemitter.

`.observe` is an API reserved for "reference cursors" created with `structure.reference(path);`

**Comment by mikaelbr** [comment]
I added clearer distinction in #64

**Comment by mikaelbr** [comment]
Fixed in #76
