### ISSUE TITLE
Distinction between 'swap' and 'change' events.

### ISSUE THREAD

**Issue by jtremback** [omniscientjs/immstruct#63]
Have not been able to figure out the whole story on the `swap` event from the documentation.

**Comment by Dashed** [comment]
They're the same now.

Documentation on conventions are now outdated.

> `change`: When data/value is updated and it existed before
> `swap`: When cursor is updated (new information is set). **Emits no values.** One use case for this is to re-render design components

**Comment by mikaelbr** [comment]
There is a difference between the current released stable, and master. So the docs is for the dist-files (or current latest), but should be updated soon when Immstruct 2.0.0 is released (some breaking changes).

**Comment by mikaelbr** [comment]
Fixed in #76
