### ISSUE TITLE
immstruct.get examples broken on API page

### ISSUE THREAD

**Issue by kswope** [omniscientjs/immstruct#75]
https://github.com/omniscientjs/immstruct/blob/master/api.md

Seems like change is happening too fast for the docs, all the examples regarding immstruct.get() are broken.  Doesn't look like there's an immstruct.get.

To make matters worse there is nothing regarding cursor.get, only cursor.set and cursor.update.  Much confusion.

**Comment by mikaelbr** [comment]
Hi! 

> Seems like change is happening too fast for the docs, all the examples regarding immstruct.get() are broken. Doesn't look like there's an immstruct.get.

Right now, the docs show the documentation for the current released version ([v1.4.1](https://github.com/omniscientjs/immstruct/blob/v1.4.1/)), so it might be confusing to see the current master branch. That being said, both the master and v1.4.1 does still have a `immstruct.get`, method. For the current stable (v1.4.1), see [L12-L17](https://github.com/omniscientjs/immstruct/blob/v1.4.1/index.js#L12-L17) and [L56-L60](https://github.com/omniscientjs/immstruct/blob/v1.4.1/index.js#L56-L60). This is a method for getting defined instances on a immstruct object. 

> To make matters worse there is nothing regarding cursor.get, only cursor.set and cursor.update. Much confusion.

There is no extensive documentation for the cursors them self, as they are actually [Immutable.js](https://github.com/facebook/immutable-js) code. This should be more clear in the documentation, but you can find it's API definition in the [Immutable.js repo](https://github.com/facebook/immutable-js/blob/master/contrib/cursor/index.d.ts).
