### ISSUE TITLE
expose immutable.js?

### ISSUE THREAD

**Issue by braindev** [omniscientjs/immstruct#86]
Would it be possible to add a function that returns a reference to the immutable.js instance that immstruct is using?  When using  immstruct from npm it'd be simple to know the immutable versions used in other places in code is the same that immstruct is using.

**Comment by mikaelbr** [comment]
Hi and thanks for the issue!

Is this to just know the version? Wouldn't say e.g. npm 3 probably dedupe so it uses the Immutable "version" you are using in your code? It'll probably do that even with npm 2, given that you install immutable explicitly I think (at least if you do it before you install immstruct).

**Comment by mikaelbr** [comment]
Is it a need while developing or dynamically being able to see the version? If it's just to see what version you have installed you can do `npm ls immutable` and it'll show all immutable versions you have.

But Immstruct by it self try to be as forgiving on the Immutable version as it can be, allowing for most possible deduping and module reuse.

**Comment by braindev** [comment]
Thanks for your quick reply!  I think I was mistaken.  There probably isn't any need for exposing immutable in immstruct.  You're right, you just need to get the order of installation right.  Sorry for false alarm.  I've been away from node/npm for a while.

**Comment by mikaelbr** [comment]
Glad it worked out! Let me know if there is anything else!
