### ISSUE TITLE
immutable-js/contrib/cursor has been deprecated

### ISSUE THREAD

**Issue by neftaly** [omniscientjs/immstruct#89]
immutable-js/contrib/cursor has been [deprecated](https://github.com/facebook/immutable-js/blob/master/contrib/cursor/README.md).

Suggest forking it, or replacing contrib/cursor with something from userland.

**Comment by mikaelbr** [comment]
It looks like https://github.com/redbadger/immutable-cursor can be a good substitute for the contrib implementation. Just need to find what the differences in API are. Hopefully, tests will catch any breaking change from our part, but this is never the less a breaking change of Immstruct.

If you want to send a PR with `immutable-cursor` that would be great!

**Comment by neftaly** [comment]
I tried updating immstruct to use immutable-cursor before making this issue, but there were a few incompatibilities. I have started making [some PRs](https://github.com/jameshopkins/atom-store/pulls) to get things going.

**Comment by neftaly** [comment]
https://github.com/jameshopkins/atom-store/pull/1

**Comment by mikaelbr** [comment]
Great stuff!

**Comment by jameshopkins** [comment]
Awesome that you guys are looking at potentially using `immutable-cursor` 👍

> I tried updating immstruct to use immutable-cursor before making this issue, but there were a few incompatibilities

What type of incompatibilities were you experiencing? The only real difference in interface between `contrib/cursor` and `immutable-cursor` from what I can remember, is [described in the documentation](https://github.com/redbadger/immutable-cursor#rationale). I'd be more than happy to help where I can with the preliminary integration.

**Comment by neftaly** [comment]
Just paths, I think - https://github.com/redbadger/immutable-cursor/pull/15

**Comment by neftaly** [comment]
Immstruct passes all tests with immutable-cursor + the PR above :)

**Comment by mikaelbr** [comment]
Good job!
